pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
        maven {
            allowInsecureProtocol true
            url 'http://repo.boox.com/repository/proxy-public/'
        }
        maven {
            allowInsecureProtocol true
            url "http://repo.boox.com/repository/maven-public/"
        }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            allowInsecureProtocol true
            url 'http://repo.boox.com/repository/proxy-public/'
        }
        maven {
            allowInsecureProtocol true
            url "http://repo.boox.com/repository/maven-public/"
        }
    }
}

rootProject.name = "PngNote2"
include ':app'
